apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcard
spec:
  selector:
    matchLabels:
      run: flashcard
  replicas: 2
  template:
    metadata:
      labels:
        run: flashcard
    spec:
      containers:
        - name: flashcard
          image: flashcard
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: flashcard-service
  labels:
    run: flashcard
spec:
  type: NodePort
  ports:
    - port: 90
      targetPort: 6000
      protocol: TCP
  selector:
    run: flashcard
