apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      run: game
  replicas: 2
  template:
    metadata:
      labels:
        run: game
    spec:
      containers:
        - name: game
          image: game
          imagePullPolicy: Always
          ports:
            - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
  labels:
    run: game
spec:
  type: NodePort
  ports:
    - port: 90
      targetPort: 2000
      protocol: TCP
  selector:
    run: game
