apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login
  name: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 2
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: login
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: login
