apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaking
spec:
  selector:
    matchLabels:
      run: matchmaking
  replicas: 2
  template:
    metadata:
      labels:
        run: matchmaking
    spec:
      containers:
        - name: matchmaking
          image: matchmaking
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: matchmaking-service
  labels:
    run: matchmaking
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    run: matchmaking
