apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  selector:
    matchLabels:
      run: profile
  replicas: 2
  template:
    metadata:
      labels:
        run: profile
    spec:
      containers:
        - name: profile
          image: profile
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    run: profile
spec:
  type: NodePort
  ports:
    - port: 90
      targetPort: 5000
      protocol: TCP
  selector:
    run: profile
