name: Deploy language

on:
  push:
    branches:
      - master
      - gke

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: language-cluster # TODO: update to cluster name
  GKE_ZONE: asia-southeast1 # TODO: update to cluster zone
  DEPLOYMENT_NAME: login # TODO: update deployment name if changed in deployment.yaml

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      # Build image
      - name: Build
        run: |-
          docker build -t login ./backend/login

      # Deploy sample image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl delete deployment --all
          kubectl apply -f ./backend/deploy-login.yaml
          sleep 10
          kubectl logs deployment/login
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
