# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Test Login microservice
      working-directory: ./backend/login  
      run: npm install; npm test
    - name: Test Flashcard microservice
      working-directory: ./backend/flashcard  
      run: npm install; npm test
    - name: Test Profile microservice
      working-directory: ./backend/profile  
      run: npm install; npm test
    - name: Test Matchmaking microservice
      working-directory: ./backend/matchmaking  
      run: npm install; npm test
